### ISSUE TITLE
example runs fail

### ISSUE THREAD

**Issue by edunseng** [ELELAB/mutatex#160]
Hi,

I have followed the instructions in the Install file and also cloned the recent repo.. After reading the paper and installation, I tested the conde on the PTEN example.
the mutatex command executed, but when trying to display the results I get the following error:

(mutatex-env) vmuser@P50VM:~/scripting/slrp/mutatex/examples/PTEN/analysis$ sudo sh do.sh
Traceback (most recent call last):
  File "/usr/local/bin/ddg2heatmap", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2heatmap')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/EGG-INFO/scripts/ddg2heatmap", line 134, in <module>
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 99, in set_default_font
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 92, in get_font_list
AttributeError: module 'matplotlib.font_manager' has no attribute 'get_fontconfig_fonts'
Traceback (most recent call last):
  File "/usr/local/bin/ddg2distribution", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2distribution')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/EGG-INFO/scripts/ddg2distribution", line 293, in <module>
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 99, in set_default_font
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 92, in get_font_list
AttributeError: module 'matplotlib.font_manager' has no attribute 'get_fontconfig_fonts'
Traceback (most recent call last):
  File "/usr/local/bin/ddg2distribution", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2distribution')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/EGG-INFO/scripts/ddg2distribution", line 293, in <module>
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 99, in set_default_font
  File "/usr/local/lib/python3.8/dist-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 92, in get_font_list
AttributeError: module 'matplotlib.font_manager' has no attribute 'get_fontconfig_fonts'

I did not changed any code, just executed after cloning. I'm using Python 3.9.5 and WSL2 .

I'd appreciate any advice.

Thanx.

**Comment by edunseng** [comment]
Test Results:

(slrp_bioinformatics) vmuser@P50VM:~/scripting/slrp/mutatex/tests/tools$ . run_tests.sh
the results directory doesn't exist in the target directory; tests will not be performed
now running  ddg2density -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/MutateX-0.8-py3.11.egg/EGG-INFO/scripts/ddg2density:24: DeprecationWarning: Please use `gaussian_kde` from the `scipy.stats` namespace, the `scipy.stats.kde` namespace is deprecated.
  from scipy.stats.kde import gaussian_kde
/home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//GA1 or file in the wrong format
 ... FAILED
now running  ddg2dg -p ../foldxsuite5/basic/2klz_1.pdb -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//GA1 or file in the wrong format
 ... FAILED
now running  ddg2distribution -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair/ -T box/home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//GA1 or file in the wrong format
 ... FAILED
now running  ddg2histo -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair/ -r QA11/home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
/home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//QA11 or file in the wrong format
 ... FAILED
now running  pdb2labels -p ../foldxsuite5/basic/2klz_1.pdb/home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
 ... PASSED
now running  ddg2logo -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair/usage: ddg2logo [-h] -p IN_PDB -d DDG_DIR -l MUTATION_LIST [-M] [-q POSITION_LIST] [-L PNGFILE] (-T THRESHOLD_STAB | -t THRESHOLD_DESTAB) [-x DEGENERACY] [-b LABELS] [-F FONT]
                [-f FONTSIZE] [-i TITLE] [-s SV] [-D DPI] [-o OUTFILE] [-v]
ddg2logo: error: one of the arguments -T/--stab-threshold -t/--destab-threshold is required
 ... FAILED
now running  ddg2heatmap -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//GA1 or file in the wrong format
 ... FAILED
now running  ddg2pdb -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//GA1 or file in the wrong format
 ... FAILED
now running  ddg2summary -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair/ -L mutations.txt/home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR:root:Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair/LA14 or file in the wrong format
ERROR:root:couldn't write output file, exiting...
 ... PASSED
now running  ddg2excel -p ../foldxsuite5/basic/2klz_1.pdb -l ../foldxsuite5/basic/mutation_list.txt -d ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//home/vmuser/anaconda3/envs/slrp_bioinformatics/lib/python3.11/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 712
  warnings.warn(
ERROR: Couldn't open energy file ../foldxsuite5/basic/results/mutation_ddgs/2klz_1_model0_checked_Repair//GA1 or file in the wrong format
 ... FAILED

**Comment by elenapapaleo** [comment]
Hi! thank you for sharing your problem. Judging from the error, it just might be that our current version is not compatible with latest matplotlib.

**Comment by edunseng** [comment]
Hi, 
Yes that would make sense. I receive errors mainly when trying to plot the results.
What's the matplotlib version, that has been used for development?
Thank you !!

**Comment by mtiberti** [comment]
hi @edunseng , please let us know if you managed to solve by switching matplotlib version

**Comment by mtiberti** [comment]
closing for inactivity
