### ISSUE TITLE
Issue when providing the font with ddg2logo

### ISSUE THREAD

**Issue by mattu90** [ELELAB/mutatex#197]
I found an issue when providing the font with the option -F with ddg2logo (but it might be a general issue). 
This is the command that I ran : 
`ddg2logo -p 1ju5_model0_checked.pdb -d final_averages/A-B/ -l mutation_list.txt  -t 1 -F Arial`
And this is the Traceback that I get:
```

> Traceback (most recent call last):
>   File "/data/user/mattia/virtualenv/mutatex_dev/bin/ddg2logo", line 4, in <module>
>     __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2logo')
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 658, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1445, in run_script
>     exec(script_code, namespace, namespace)
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/MutateX-0.8-py3.8.egg/EGG-INFO/scripts/ddg2logo", line 284, in <module>
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 99, in set_default_font
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 93, in get_font_list
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/MutateX-0.8-py3.8.egg/mutatex/utils.py", line 93, in <listcomp>
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/matplotlib-3.5.1-py3.8-linux-x86_64.egg/matplotlib/font_manager.py", line 737, in get_name
>     return get_font(findfont(self)).family_name
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/matplotlib-3.5.1-py3.8-linux-x86_64.egg/matplotlib/font_manager.py", line 1424, in get_font
>     return _get_font(filename, hinting_factor,
>   File "/data/user/mattia/virtualenv/mutatex_dev/lib/python3.8/site-packages/matplotlib-3.5.1-py3.8-linux-x86_64.egg/matplotlib/font_manager.py", line 1405, in _get_font
>     return ft2font.FT2Font(
> RuntimeError: In FT2Font: Can not load face.  Unknown file format.

```

**Comment by mtiberti** [comment]
fixed in #200
