### ISSUE TITLE
MutateX crashes when trying to fill in undefined chain names, but A chains already exists

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/mutatex#201]
During PDB preparation and check, mutatex checks if all residues have an assigned chain identifier. If this is not the case, it tries to assign all the chains that do not have an identifier to chain 'A'. This can be problematic for cases in which multiple chains are in the PDB, and only one of them is without chain identifier, and chain A is already defined. This causes mutatex to error out with a misleading error message:

```
INFO:root:checking models in pdb file
WARNING:root:at least one residue in model 0 in pdb file has no chain identifier. Will be defaulted to A.
ERROR:root:Couldn't load PDB structure; exiting...
```

what is actually happening internally, is that BioPython refuses to assign a chain that already exists (line 603 in `utils.py`):

```
>>> cs[2].id = 'A'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/envs/mutatex/lib/python3.10/site-packages/Bio/PDB/Entity.py", line 173, in id
    raise ValueError(
ValueError: Cannot change id from ` ` to `A`. The id `A` is already used for a sibling of this entity.
```

I feel like the best solution would be just to error out if we find residues with no chain identifier, and let the user fix it in any way they see fit. This would be helpful to avoid further problems or misunderstandings in what mutatex ends up doing

**Comment by elenapapaleo** [comment]
I am closing this for now since it doesn't seem we have the manpower to address it
